### ISSUE TITLE
Conflict with codeniko/JsonPathKt library

### ISSUE THREAD

**Issue by curioustechizen** [eygraber/JsonPathKt#73]
A tiny bit of history:

1. I've been using https://github.com/codeniko/JsonPathKt to implement Json-Path based parsing in my Android app. I make liberal use of the `com.nfeld.jsonpathkt.extension.read` method
2. Then I had the requirement to implement a similar parsing in a new feature that is being implemented with KMP (Android and iOS) .After researching multiplatform JsonPath libraries I came across this one.
3. I implemented the multiplatform case using `jsonpathkt.kotlinx` package

### Problem statement

Now comes the real problem: I cannot build my Android app anymore because I have some (Android-only) modules depending on `com.nfeld.jsonpathkt:jsonpathkt:2.0.1` while my KMP modules depend on `com.eygraber:jsonpathkt-kotlinx:3.0.1`.

Including both dependencies results in duplicate classes (this is expected). My problem is I cannot exclude the `com.nfeld.jsonpathkt` dependency because then I don't have the `read` extension anymore.

Is there a way to work around my problem without migrating all my existing Android-only modules to use `jsonpathkt.kotlinx`?

**Comment by eygraber** [comment]
Is the issue that you don't want to make any code changes because the API changed, or because you need to use Jackson (which is what codeniko's implementation used)?

This library does provide a Jackson artifact, but the API is different so you would need code changes. If you want minimal code changes you can try making an extension function that emulates the old API.

**Comment by curioustechizen** [comment]
I just looked at the implementation and now I see that I had misunderstood the whole thing.

I had assumed that `com.eygraber:jsonpathkt-kotlinx:3.0.1` depends on `com.nfeld.jsonpathkt:jsonpathkt:2.0.1` and that I get the symbols from that latter in my app because of a transitive dependency.

However now I see the implementation, it turns out that `com.eygraber:jsonpathkt-kotlinx:3.0.1` does not depend on the other library at all. Instead it defines the same symbols with the same package name, but it omits some extension APIs (because those extensions depend on Jackson and probably don't make sense in a multiplatform context). So even a simple Gradle exclude is not going to do what I originally thought it does. 

I think it should be relatively simple to migrate my existing implementations to the new API by creating some extension functions so that's the path that I'll take.

 Closing this issue. Thanks for your explanation - it was helpful in me to uncover my misunderstanding.

**Comment by curioustechizen** [comment]
For completeness, I was able to repurpose [this](https://github.com/eygraber/JsonPathKt/blob/3414574ca6f8283c0d551278e3eee0c8c561ed18/jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/TestUtils.kt#L26C1-L32C2) utility function (it plays the exact role as `com.nfeld.jsonpathkt.extension.read` method).

The rest was minor changes.

```kt
// Here, practicalTipsJson is the input string

// Before:
val parsed = JsonPath.parse(practicalTipsJson)
val tipTitles = parsed?.read<List<String>>("$.tips..title.$langSuffix")
val tipContents = parsed?.read<List<String>>("$.tips..content.$langSuffix")

// After: Here read is defined as the resolveAsType utility function linked to above
val parsed = Json.parseToJsonElement(practicalTipsJson)
val tipTitles = parsed.read<List<String>>("$.tips..title.$langSuffix")
val tipContents = parsed.read<List<String>>("$.tips..content.$langSuffix")
```

**Comment by daniel-dewa** [comment]
I think this library took a wrong decision keeping the package name, as it breaks any projects that still depend (or dependencies depend) on `com.nfeld.jsonpathkt:jsonpathkt:2.0.1`. The correct thing to do, would have been to rename the package as soon as there was a breaking change, e.g, from `com.nfeld.jsonpathkt` to `com.eygraber.jsonpathkt`.
But now it is too late.

**Comment by eygraber** [comment]
Yes, it was an unfortunate oversight. This was originally planned as a contribution to the original repo, and when we decided to fork we missed changing the package.
